games:
# full example
- url: http://gamedevgr/exquisite-corpse
  rev: example-1
  build:
    mac: "echo 1"
    windows: null
  run:
    mac: python3 example_1.py
    linux: ./example_1.py
# examples with only the required fields
- url: http://gamedevgr/exquisite-corpse
  rev: example-2
  run:
    mac: ./example_2.py
- url: http://gamedevgr/exquisite-corpse
  rev: example-3
  run:
    mac: ./example_3.py
